name: WebViewWhitelistBug
options:
  bundleIdPrefix: com.example.whitelistbug
  deploymentTarget:
    iOS: "15.0"

targets:
  WebViewWhitelistBug:
    type: application
    platform: iOS
    sources:
      - Sources
    postCompileScripts:
      - name: Copy www to bundle
        script: |
          cp -R "${SRCROOT}/Resources/www" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/www"
        basedOnDependencyAnalysis: false
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.whitelistbug.webview
        MARKETING_VERSION: "1.3.0"
        CURRENT_PROJECT_VERSION: 4
        CODE_SIGNING_ALLOWED: "NO"
