name: WebViewWhitelistBug
options:
  bundleIdPrefix: com.example.whitelistbug
  deploymentTarget:
    iOS: "15.0"

targets:
  WebViewWhitelistBug:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - path: Resources
        excludes:
          - "*.plist"
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.whitelistbug.webview
        MARKETING_VERSION: "1.1.0"
        CURRENT_PROJECT_VERSION: 2
        CODE_SIGNING_ALLOWED: "NO"
