name: WebViewWhitelistBug
options:
  bundleIdPrefix: com.example.whitelistbug
  deploymentTarget:
    iOS: "15.0"

targets:
  WebViewWhitelistBug:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - path: Resources/www
        type: folder
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.whitelistbug.webview
        MARKETING_VERSION: "1.2.0"
        CURRENT_PROJECT_VERSION: 3
        CODE_SIGNING_ALLOWED: "NO"
